apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  image:
  - pullPolicy: {{ .Values.image.pullPolicy }}
  ports:
  - port: {{ .Values.service.port }}
    protocol:  {{ .Values.service.protocol }}
    targetPort:  {{ .Values.service.targetPort }}
  resources: 
    requests:
    - cpu: {{ .Values.resources.requests.cpu }}
      memory: {{ .Values.resources.requests.memory }}
    limits: 
    - memory: {{ .Values.resources.limits.memory }}
      cpu: {{ .Values.resources.limits.cpu }}
