apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends-latest
  namespace: {{ .Values.namespace.name }} 

spec: 
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      ports:
      - port: {{ .Values.service.port }} 
      protocol: TCP
      targetPort: {{ .Values.service.port }}
      type: {{ .Values.service.type }} 
      containers:
        name: techtrends-latest
        resources:
{{ toYaml .Values.resources | indent 12 }}
